apiVersion: temporal.io/v1alpha1
kind: WorkerDeployment
metadata:
  name: temporal-worker-1
  labels:
    app: temporal-worker-1
spec:
  replicas: 1
  workerOptions:
    connectionRef:
      name: temporal
    temporalNamespace: default
  rollout:
    strategy: AllAtOnce
  template:
    metadata:
      labels:
        app: temporal-worker-1
    spec:
      serviceAccountName: temporal-worker-1
      containers:
        - name: temporal-worker-1
          image: k3d-registry:5000/temporal-worker-1:f2bbfb7
          imagePullPolicy: Always
          env:
            - name: TEMPORAL_HOST
              value: "temporal-frontend.temporal.svc.cluster.local:7233"
            - name: TEMPORAL_TASK_QUEUE
              value: "temporal-worker-1-queue"
            - name: TEMPORAL_USE_VAULT_AUTH
              value: "false"
            - name: VAULT_ADDR
              value: "http://vault.vault.svc.cluster.local:8200"
            - name: VAULT_K8S_AUTH_PATH
              value: "auth/kubernetes"
            - name: VAULT_K8S_ROLE
              value: "temporal-worker-1"
            - name: VAULT_JWT_SIGN_ROLE
              value: "temporal-worker-1"
            - name: VAULT_JWT_AUDIENCE
              value: "temporal"
            - name: VAULT_JWT_SUBJECT
              value: "svc:temporal-worker-1"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
