apiVersion: slack.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      name: slack-creds
      namespace: crossplane-system
      key: slack_operator
  pollInterval: 5m
