apiVersion: v1
kind: ServiceAccount
metadata:
  name: slack-vault-auth
  namespace: crossplane-system
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: local-vault
  namespace: crossplane-system
spec:
  address: http://vault.vault.svc.cluster.local:8200
  skipTLSVerify: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: slack-vault-auth
  namespace: crossplane-system
spec:
  vaultConnectionRef: local-vault
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: crossplane-slack
    serviceAccount: slack-vault-auth
    audiences:
      - vault
