apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: temporal-worker-1
  namespace: argocd
  annotations:
    # After temporal server (wave 4)
    argocd.argoproj.io/sync-wave: "5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ksamay-Budy/local-k8-cluster-1
    targetRevision: HEAD
    path: apps/temporal-worker-1/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: temporal
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
