# provider-slack-conversation v2.0.1 omits permissions for its ProviderConfig
# and ProviderConfigUsage resources from its package metadata. Crossplane uses
# these objects to configure and track managed resources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: provider-slack-conversation-providerconfigusage
rules:
  - apiGroups:
      - slack.crossplane.io
    resources:
      - providerconfigs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - slack.crossplane.io
    resources:
      - providerconfigusages
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - slack.crossplane.io
    resources:
      - providerconfigusages/status
    verbs:
      - get
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: provider-slack-conversation-providerconfigusage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: provider-slack-conversation-providerconfigusage
subjects:
  - kind: ServiceAccount
    name: provider-slack-conversation-1ce26888ff09
    namespace: crossplane-system
