apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ob1-tf-eks-de-v2-llm-1-ns-1
resources:
  - ../base
patches:
  - target:
      kind: Deployment
      name: temporal-payload-relay
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/1/value
        value: ob1-temporal-llm-router-1-ns-1
      - op: replace
        path: /spec/template/spec/containers/0/env/2/value
        value: ob1-llm-router-nexus-queue-1
      - op: replace
        path: /spec/template/spec/containers/0/env/3/value
        value: temporal-payload-relay-llm-router
      - op: replace
        path: /spec/template/metadata/annotations/vault.hashicorp.com~1role
        value: temporal-payload-relay-llm-router
