# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: temporal-worker-controller
#   namespace: argocd
#   annotations:
#     # Install after the CRDs are present.
#     argocd.argoproj.io/sync-wave: "6"
#   finalizers:
#     - resources-finalizer.argocd.argoproj.io
# spec:
#   project: default
#   sources:
#     - repoURL: registry-1.docker.io/temporalio
#       chart: temporal-worker-controller
#       targetRevision: "0.26.0"
#       helm:
#         valueFiles:
#           - $values/infra/temporal-worker-controller/values.yaml

#     - repoURL: https://github.com/prsanghavi/local-k8-cluster-1
#       targetRevision: HEAD
#       ref: values

#   destination:
#     server: https://kubernetes.default.svc
#     namespace: temporal

#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true
