apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: temporal-codec-server
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
    - host: temporal.local
      http:
        paths:
          - path: /codec
            pathType: Prefix
            backend:
              service:
                name: temporal-codec-server
                port:
                  name: http
